name: Code Quality Check

on:
  pull_request:
    branches:
      - main

jobs:
  code-quality-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install streamlit gpt4all python-dotenv

    - name: Executar Flake8
      run: |
        flake8 main.py --max-line-length=120 --ignore=E203,W503
